name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
    - name: Show Xcode version
      run: xcodebuild -version
    - name: Resolve Swift Package Dependencies
      run: swift package resolve
    - name: Build for iOS Simulator
      run: |
        xcodebuild build \
          -scheme mParticle-Mixpanel \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 17,OS=latest' \
          CODE_SIGNING_ALLOWED='NO'
    - name: Run tests for iOS Simulator
      run: |
        xcodebuild test \
          -scheme mParticle-Mixpanel \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 17,OS=latest' \
          -enableCodeCoverage YES \
          CODE_SIGNING_ALLOWED='NO'

  pod-lint:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
    - name: CocoaPods Lint
      run: pod lib lint mParticle-Mixpanel.podspec --allow-warnings
